package me.mitkovic.kmp.netpulse.domain.model

data class UserLocation(
    val ip: String?,
    val network: String?,
    val version: String?,
    val city: String?,
    val region: String?,
    val regionCode: String?,
    val country: String?,
    val countryName: String?,
    val countryCode: String?,
    val countryCodeIso3: String?,
    val countryCapital: String?,
    val countryTld: String?,
    val continentCode: String?,
    val inEu: Boolean?,
    val postal: String?,
    val latitude: Double,
    val longitude: Double,
    val timezone: String?,
    val utcOffset: String?,
    val countryCallingCode: String?,
    val currency: String?,
    val currencyName: String?,
    val languages: String?,
    val countryArea: Double?,
    val countryPopulation: Long?,
    val asn: String?,
    val org: String?,
    val timestamp: Long,
)
